---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine
inputs:
  - name: demo-onlinestore-user
outputs:
  - name: build
run:
  path: sh
  args:
    - demo-onlinestore-user/ci/tasks/build.sh
params:
  _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom